irony-server: Adds -fspell-checking to compiler flags if not already added.
libclang does not by default check/report spelling errors.

I.e. something like
std::ting str;
will yield:
error: no type named 'tring' in namespace 'std'

Adding -fspell-check improves the error message to:
error: no type named 'tring' in namespace 'std'; did you mean 'string'?

It also finds the location of the reference (std::string in this case),
but that's less relevant.

It's turned off by default because it increases parsing time. Clang itself
has it on by default though.

This extended reporting is extremely useful for flycheck-irony.